# Generated by Django 4.1.1 on 2022-10-07 17:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('triggers', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AppSessionCountCondition',
            fields=[
                ('condition_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='triggers.condition')),
                ('app', models.CharField(blank=True, choices=[('mobile', 'Mobile'), ('desktop', 'Desktop')], max_length=16, verbose_name='application')),
                ('count', models.PositiveIntegerField(verbose_name='app session count')),
            ],
            options={
                'abstract': False,
                'base_manager_name': 'objects',
            },
            bases=('triggers.condition',),
        ),
        migrations.CreateModel(
            name='AppSessionStartedEvent',
            fields=[
                ('event_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='triggers.event')),
                ('app', models.CharField(blank=True, choices=[('mobile', 'Mobile'), ('desktop', 'Desktop')], max_length=16, verbose_name='application')),
            ],
            options={
                'abstract': False,
                'base_manager_name': 'objects',
            },
            bases=('triggers.event',),
        ),
        migrations.CreateModel(
            name='SendMessageAction',
            fields=[
                ('action_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='triggers.action')),
                ('text', models.TextField(verbose_name='text')),
            ],
            options={
                'verbose_name': 'send message',
                'verbose_name_plural': 'send messages',
            },
            bases=('triggers.action',),
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creation_datetime', models.DateTimeField(default=django.utils.timezone.now, verbose_name='created at')),
                ('text', models.TextField(verbose_name='text')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', related_query_name='message', to=settings.AUTH_USER_MODEL, verbose_name='user')),
            ],
            options={
                'verbose_name': 'message',
                'verbose_name_plural': 'messages',
            },
        ),
        migrations.CreateModel(
            name='AppSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app', models.CharField(choices=[('mobile', 'Mobile'), ('desktop', 'Desktop')], max_length=16, verbose_name='application')),
                ('start_datetime', models.DateTimeField(db_index=True, default=django.utils.timezone.now, verbose_name='started at')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='app_sessions', related_query_name='app_session', to=settings.AUTH_USER_MODEL, verbose_name='user')),
            ],
            options={
                'verbose_name': 'app session',
                'verbose_name_plural': 'app sessions',
            },
        ),
    ]
