# Generated by Django 3.2.16 on 2022-12-21 20:50

import datetime

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('triggers', '0002_auto_20221021_2046'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='delay',
            field=models.DurationField(blank=True, default=datetime.timedelta(0), help_text='Delay from the moment when the event actually happened until it should be handled.', verbose_name='delay'),
        ),
    ]
