# Generated by Django 3.2.20 on 2024-06-04 05:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('triggers', '0003_event_delay'),
    ]

    operations = [
        migrations.AlterField(
            model_name='action',
            name='trigger',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='actions', related_query_name='action', to='triggers.trigger', verbose_name='trigger'),
        ),
    ]
