# Generated by Django 3.2.20 on 2024-06-11 08:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('triggers', '0005_alter_action_triggers'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='action',
            name='trigger_old',
        ),
    ]
