# Generated by Django 3.2.25 on 2025-05-19 13:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('triggers', '0006_remove_action_trigger_old'),
    ]

    operations = [
        migrations.CreateModel(
            name='TriggerLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True, verbose_name='timestamp')),
                ('run_id', models.UUIDField(db_index=True, help_text='Trigger execution identifier', verbose_name='run ID')),
                ('entity_type', models.CharField(choices=[('event', 'Event'), ('trigger', 'Trigger'), ('condition', 'Condition'), ('action', 'Action')], max_length=20, verbose_name='entity type')),
                ('entity_id', models.PositiveIntegerField(verbose_name='entity ID')),
                ('entity_class_path', models.CharField(max_length=255, verbose_name='entity class path')),
                ('entity_name', models.CharField(blank=True, max_length=255, verbose_name='entity name')),
                ('stage', models.CharField(choices=[('fire', 'Fire initiated'), ('should_be_fired', 'Should be fired check'), ('trigger_filter', 'Trigger filtering'), ('condition_filter', 'Condition filtering'), ('signal_sent', 'Signal sent'), ('task_created', 'Task created'), ('handle_start', 'Handle start'), ('condition_check', 'Condition satisfied check'), ('action_perform', 'Action perform')], max_length=30, verbose_name='stage')),
                ('result', models.BooleanField(blank=True, null=True, verbose_name='result')),
                ('details', models.JSONField(blank=True, default=dict, null=True, verbose_name='details')),
                ('trigger', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='triggers.trigger', verbose_name='trigger')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='trigger_logs', to=settings.AUTH_USER_MODEL, verbose_name='user')),
            ],
            options={
                'verbose_name': 'trigger log',
                'verbose_name_plural': 'trigger logs',
                'ordering': ['-timestamp'],
            },
        ),
    ]
