# Generated by Django 4.1.2

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("contenttypes", "0002_remove_content_type_name"),
        ("triggers", "0006_remove_action_trigger_old"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="TriggerRun",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("run_id", models.CharField(db_index=True, max_length=32, unique=True, verbose_name="run id")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("enqueued", "Enqueued"),
                            ("started", "Started"),
                            ("success", "Success"),
                            ("conditions_failed", "Conditions failed"),
                            ("user_not_found", "User not found"),
                            ("action_failed", "Action failed"),
                        ],
                        default="enqueued",
                        max_length=32,
                        verbose_name="status",
                    ),
                ),
                ("event_object_id", models.BigIntegerField(blank=True, null=True, verbose_name="event object id")),
                ("steps", models.JSONField(blank=True, default=list, verbose_name="steps")),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="created at")),
                ("started_at", models.DateTimeField(blank=True, null=True, verbose_name="started at")),
                ("finished_at", models.DateTimeField(blank=True, null=True, verbose_name="finished at")),
                (
                    "event_content_type",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="contenttypes.contenttype",
                        verbose_name="event content type",
                    ),
                ),
                (
                    "trigger",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="runs",
                        related_query_name="run",
                        to="triggers.trigger",
                        verbose_name="trigger",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="trigger_runs",
                        related_query_name="trigger_run",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="user",
                    ),
                ),
            ],
            options={
                "verbose_name": "trigger run",
                "verbose_name_plural": "trigger runs",
                "ordering": ("-created_at",),
            },
        ),
        migrations.AddIndex(
            model_name="triggerrun",
            index=models.Index(fields=["user", "created_at"], name="triggers_co_user_id_f3c479_idx"),
        ),
        migrations.AddIndex(
            model_name="triggerrun",
            index=models.Index(fields=["status", "created_at"], name="triggers_co_status_ef1cf9_idx"),
        ),
        migrations.AddIndex(
            model_name="triggerrun",
            index=models.Index(fields=["trigger", "created_at"], name="triggers_co_trigger_267f1d_idx"),
        ),
    ]
