name: Test
on: push
jobs:
  test:
    runs-on: macos-latest
    strategy:
      matrix:
        python-version: [ "3.7", "3.8", "3.9", "3.10", "3.11" ]
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install poetry
        run: python -m pip install poetry -U
      - name: Generate requirements.txt
        run: poetry export -f requirements.txt --with dev --output requirements.txt
      - name: Install dependencies
        run: python -m pip install -r requirements.txt
      - name: Run flake8
        run: flake8 triggers tests
      - name: Run isort
        run: isort --check triggers tests
      - name: Run mypy
        run: mypy triggers tests
      - name: Run pytest
        run: python -m pytest --cov-report xml
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v3
        with:
            token: ${{ secrets.CODECOV_TOKEN }}
            verbose: true
