name: Test
on: push
jobs:
  test:
    runs-on: macos-latest
    strategy:
      matrix:
        python-version: [ "3.7", "3.8", "3.9", "3.10", "3.11" ]
    steps:
      - uses: actions/checkout@v2
      - name: Install poetry
        run: python3 -m pip install poetry -U
      - name: Set up Python ${{ matrix.python-version }}
        run: poetry env use ${{ matrix.python-version }}
      - name: Install dependencies
        run: poetry install --with dev
      - name: Run flake8
        run: poetry run flake8 triggers tests
      - name: Run isort
        run: poetry run isort --check triggers tests
      - name: Run mypy
        run: poetry run mypy triggers tests
      - name: Run pytest
        run: poetry run pytest --cov-report xml
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v3
        with:
            token: ${{ secrets.CODECOV_TOKEN }}
            verbose: true
