name: Test
on: push
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install dependencies
        run: poetry install --with dev
      - name: Run flake8
        run: poetry run flake8 triggers
      - name: Run mypy
        run: poetry run mypy triggers
